# Generated by Django 3.2.5 on 2022-04-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='heading',
            new_name='tagline_1',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='tagline',
            new_name='tagline_2',
        ),
        migrations.AddField(
            model_name='index',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='index',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='index',
            name='contact_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='index',
            name='facebook_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='index',
            name='instagram_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='index',
            name='linkedin_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='index',
            name='main_heading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='index',
            name='portfolio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='index',
            name='services_heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='index',
            name='subscribe_heading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='index',
            name='team_heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='index',
            name='twitter_link',
            field=models.CharField(default='', max_length=150),
        ),
    ]
