# Generated by Django 3.2.5 on 2022-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220411_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='about',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='address',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='contact_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='facebook_link',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='instagram_link',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='linkedin_link',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='index',
            name='main_heading',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='portfolio',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='services_heading',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='subscribe_heading',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='tagline_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='tagline_2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='team_heading',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter_link',
            field=models.TextField(default='', max_length=150),
        ),
    ]
