# Generated by Django 3.2.5 on 2022-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220411_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(max_length=50)),
                ('client_logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='about',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='contact_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='facebook_link',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='instagram_link',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='linkedin_link',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='main_heading',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='portfolio',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='services_heading',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='subscribe_heading',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='team_heading',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter_link',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
