# Generated by Django 3.2.5 on 2022-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20220411_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial')),
                ('testimonial', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
