# Generated by Django 3.2.5 on 2022-04-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_team_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='tagline_1',
            new_name='tagline',
        ),
        migrations.RemoveField(
            model_name='index',
            name='tagline_2',
        ),
    ]
