# Generated by Django 4.0.6 on 2022-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_contact_service_stat_remove_index_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='images/team/worddealers.png', null=True, upload_to='team'),
        ),
    ]
