# Generated by Django 4.0.3 on 2022-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_achievements_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='stats',
            field=models.ManyToManyField(blank=True, to='index.stat'),
        ),
    ]
